(*
let world = 'world'
let a = :ok;
print("Hello, {world}")
inspect(match a {
    :ok => "ok",
    :notok => "not ok"
})
*)
sc = ";";

(* compiler magic *)
stratom = __;

ifatom = kw:"if" expr "{" [^"}"]stmt;

atom = stratom | ifatom | blockatom | matchatom;

(* prec climber *)
expr = prec_climb[* / - +] atom;

letstmt = kw:"let" ident:* "=" expr;
exprstmt = expr;
stmt = sc | letstmt | exprstmt;
program = [^eof](stmt program);