(*
let world = 'world'
let a = :ok;
print("Hello, {world}")
inspect(match a {
    :ok => "ok",
    :notok => "not ok"
})
*)
letstmt = kw:"let" ident:* "=" expr [";";"?;
exprstmt = expr ";"?;
stmt = letstmt | exprstmt;
program = [^eof](stmt program);