(*
let world = 'world'
let a = :ok;
print("Hello, {world}")
inspect(match a {
    :ok => "ok",
    :notok => "not ok"
})
*)
sc = ";";

(* prec climber *)
expr = prec_cli;

letstmt = kw:"let" ident:* "=" expr;
exprstmt = expr;
stmt = sc | letstmt | exprstmt;
program = [^eof](stmt program);